### ISSUE TITLE
Patching PYPOWER 

### ISSUE THREAD

**Issue by jrupamathi** [pnnl/tesp#1]
The suggested patch isn't working. I still get the same error:
![image](https://cloud.githubusercontent.com/assets/6997177/26525155/4ddea2fc-4303-11e7-84ee-479d83c13b4a.png)

Any help in resolving this is appreciated.

**Comment by temcdrm** [comment]
The last message indicates that your copy of ext2int.py isn't really Python code.  Did it come from a right-click "save as" operation from the GitHub web site?  If so, please try copying the Python files from a clone of the repository (i.e. use the command-line version of Git, or possibly SourceTree).

**Comment by jrupamathi** [comment]
Thank you so much. That worked. But I get struck with an other series of error message as shown below:

![image](https://cloud.githubusercontent.com/assets/6997177/26690294/9186939a-46ad-11e7-9828-4a2aceeeabc5.png)

![image](https://cloud.githubusercontent.com/assets/6997177/26690316/a919a6c8-46ad-11e7-82b3-797d9abb307c.png)

![image](https://cloud.githubusercontent.com/assets/6997177/26690326/b7549fc2-46ad-11e7-87c1-52561e6048ab.png)

![image](https://cloud.githubusercontent.com/assets/6997177/26690340/c5649f54-46ad-11e7-9a92-9098e847a25e.png)


I tried reinstalling as the error message said. But this didn't work out.

Thanks,
Rupa

**Comment by temcdrm** [comment]
Rupa – that appears to be a symptom of overlooking this step from the install\windows\readme.txt file:

4.  Unzip the archive c:\tesp\install\windows\MinGWredist.zip archive to c:\gridlab-d\install64\bin

_________________________

Tom McDermott, Ph.D., PE, FIEEE
Chief Engineer, Integration
Electricity Infrastructure
Pacific Northwest National Laboratory
Phone: 509-375-4434
Thomas.McDermott@pnnl.gov

**Comment by jrupamathi** [comment]
Hi,
The files were extracted to a separate folder which is why it didn't work.
As per your suggestion, I directly extracted the files. It is all working now.

Thank you very much,
Rupa
