### ISSUE TITLE
Make new `rename_obj()` API

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#100]
We need to add an API to rename an object BUT we need to do this correctly we need to not only change the name of the object but also the string in any other object that references the name of the object we're changing. This is likely to be non-trivial.

**Comment by d3j331** [comment]
Is this for modifier.py?

**Comment by trevorhardy** [comment]
I think so.

**Comment by trevorhardy** [comment]
Complete in 1.3.2.
