### ISSUE TITLE
Add syntax sugar for deleting value from GridLAB-D objects with GLMModifier

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#106]
To use more Pythonic conventions, it would be nice to wrap GLMModifer.del_object_attr() in such a way such that the following three calls had the same effect:

```
del_object_attr('house', <house name>, 'floor_area)
house_obj['floor_area'] = None
house_obj['floor_area'] = ''
```

**Comment by d3j331** [comment]
These are implemented
  del_object_attr('house', <house name>, 'floor_area)
  house_obj['floor_area'] = None

This can not be used this way, is it possible to use a blank string in GLM because of datatype
  house_obj['floor_area'] = ''
