### ISSUE TITLE
GLMModifier needs to support `class player {...`

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#110]
GridLAB-D supports the definition of new classes and is commonly used for player transforms _a la_

```
class player {
    double value;
}
```
"class" is not a GridLAB-D module or class and thus doesn't appear when we ask GridLAB-D for all the modules and classes. Support for it to appear in the .glms needs to be manually added.

**Comment by trevorhardy** [comment]
Done but not merged into `develop` yet.

**Comment by d3j331** [comment]
Has been merge into develop.
