### ISSUE TITLE
install/MacOSX missing files

### ISSUE THREAD

**Issue by nathantgray** [pnnl/tesp#12]
install/MacOSX is missing the files described in the following steps in the readme file:
"
4.  Unzip the archive ~/tesp/install/MacOSX/Archive_usr_local_share.zip to /usr/local/share
5a.  Manually create the directory /usr/local/opt/jsoncpp
5b.  Unzip the archive ~/tesp/install/MacOSX/Archive_usr_local_opt_jsoncpp.zip to /usr/local/opt/jsoncpp
"

**Comment by temcdrm** [comment]
The readme file was out of date.

Front Page and Installation Directions: https://github.com/pnnl/tesp

Terse Installation Directions:

  1) Install Python 3.6 or later
  2) pip install tesp_support --upgrade
  3) choose a platform-dependent installer from: https://github.com/pnnl/tesp/releases
