### ISSUE TITLE
Add option to have network plot coordinates fed back into .glm

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#121]
As part of plotting the network model networkx defines locations for all the nodes in the network. Though the algorithm used is unlikely to be highly realistic for power system purposes, it can be better than nothing. We should add a feature to the `GLModifier.model.plot_model()` call to allow these coordinates to feed back up from the networkx graph to the .glm.

**Comment by d3j331** [comment]
networkx plot locations might change every time is generated, but I think it can be done.

**Comment by trevorhardy** [comment]
Monish made these commits in the "uvm" branch and they need to be pulled into the mainline of TESP.

We need to test the case where not all objects have a location defined to make sure the lay-out engine can fill in any gaps.

**Comment by jk1066** [comment]
Tested on UVM feeder, generates plot immediately.
