### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by ikdmob** [pnnl/tesp#13]
Hi,
I have installed tesp on my ubuntu virtual machine using the installer, however when I try to run the examples it does not work and the log files have this error "fncs_player: error while loading shared libraries: libfncs.so.1: cannot open shared object file: No such file or directory"
Please what could be the cause for this?

**Comment by ikdmob** [comment]
Thanks for the response Tom.
This is Ubuntu 16.04.
No it did not present an error message when I installed from the released installer.
Yes I have a file called /usr/local/lib/libfncs.so.1.1.1. Please how do I manually create symlinks?

**Comment by ikdmob** [comment]
I also have the same problem in my windows machine. Please how can I solve this?

**Comment by temcdrm** [comment]
Please try one of the new installers for 0.3.2, Windows or Linux, at https://github.com/pnnl/tesp/releases.  

Also please note the updated instructions on https://tesp.readthedocs.io/en/latest/

**Comment by ikdmob** [comment]
It works now, thanks!
