### ISSUE TITLE
data.py is full of `+` for string concatenation rather than `os.path.join()`

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#139]
All kinds of pathing problems on Windows are created by using `+` instead of `os.path.join()`. Many of the paths defined in data.py that are intended to be user-accessible are unusable as they contain mixed slashes (`/`, `\`).

**Comment by trevorhardy** [comment]
Tested to be working on macOS and put into PR #142.

**Comment by d3j331** [comment]
Since been rectified by another commit
