### ISSUE TITLE
Add group_recorder to master_settings.JSON

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#141]
When Jessica added a group_recorder using GLMModifier, she got a warning that "group_recorder" was not a recognized object. This implies it wasn't in the master_setting.json (now glm_classes.json). We need to double-check that it's there and see if we can replicate the warning.

**Comment by trevorhardy** [comment]
Mitch sees it in glm_classes.json so definitely need to verify that no warning is produced.

**Comment by trevorhardy** [comment]
@jk will test this on her code that was causing the problem.

**Comment by jk** [comment]
@trevorhardy who are you?

**Comment by trevorhardy** [comment]
Ahh, sorry. Got this assigned to the wrong person. My bad.

**Comment by jk1066** [comment]
Tested with modified version of feeder_generator.py, no errors. 

```
         group_recorder_params = {
            'group': 'class=house',
            'name': 'air_temp_recorder',
            'file': 'airtemp.csv',
            'interval': 300,
            'property': 'air_temperature'
            }
        
        group_recorder_obj = glmMod.add_object('group_recorder', 'air_temp', group_recorder_params)
```

Output on .glm:
```
object group_recorder {
  name air_temp;
  group class=house;
  name air_temp_recorder;
  file airtemp.csv;
  interval 300;
  property air_temperature;
}

```
