### ISSUE TITLE
Error messages generated in model_GLM.py can be misleading

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#144]
When adding a new object using `add_object()`, if [`set_instance()`](https://github.com/pnnl/tesp/blob/628ef8d14c3fa729a126fd5be3f97327d16085c4/src/tesp_support/tesp_support/api/model_GLM.py#L465) fails the warning message returned states that the object being added "must be a new object". Through the experience of the user we have found that `set_instance()` can also fail if the `params` parameter is malformed though the error message provided will still be the same, causing the user to look for a problem in the wrong place. 

We need to do input validation before calling the `set_instance()` method or as part of the `except` clause so that the error message provided is meaningful and accurate.

This validation needs to be added to all parts of model_GLM.py to catch a wider variety of causes of failure.

**Comment by jk1066** [comment]
`set_instance()` within entity.py has a check on the params (lines 175 to 185) that looks like it would work well here, in `set_object_instance()` within model_GLM.py. That check is:

>             for attr in params:
>                 item = self.find_item(attr)
>                 if type(item) == Item:
>                     try:
>                         _ = instance[attr]
>                     except:
>                         if type(attr) == str:
>                             instance[attr] = {}
>                         else:
>                             print("Attribute id is not a string in", self.entity, "named", object_name)
>                             continue

                            
Let me know if this seems sufficient and I'll add it to `set_object_instance()`.

**Comment by d3j331** [comment]
Fix and found and new class OEntity the allows object to a another instance
