### ISSUE TITLE
issue with install from "wget --no-check-certificate https://raw.githubusercontent.com/pnnl/tesp/main/scripts/tesp.sh"

### ISSUE THREAD

**Issue by HayHazel** [pnnl/tesp#146]
I'm trying to install tesp following the instructions given in https://tesp.readthedocs.io/en/latest/Installing_Building_TESP.html.

It's having errors with ns-3, fncs, and klu. 

fncs gives:
 tesp.patch:32620: new blank line at EOF.
+
warning: 1 line adds whitespace errors.
Apply patches for repository fncs
Patch file at fncs/tesp.patch

ns-3 gives no errors but helics-ns3 gives:
EAD is now at cdceb94 Bug fix on the Send function scheduled message event time (#48)
Apply patches for repository ns-3-dev/contrib/helics
Patch file at ns-3-dev/contrib/helics/tesp.patch

KLU SOLVER gives:
svn: E170013: Unable to connect to a repository at URL 'https://github.com/gridlab-d/tools/tree/klu-build-update/solver_klu/source/KLU_DLL'
svn: E160013: '/gridlab-d/tools/tree/klu-build-update/solver_klu/source/KLU_DLL' path not found

is there another file i should be using for install or is there an update to tesp.sh coming shortly?

**Comment by trevorhardy** [comment]
We're getting ready to make a minor update release; let me see if I can replicate these errors.

**Comment by HayHazel** [comment]
many thanks

**Comment by d3j331** [comment]
github no longer allows this export
`svn export https://github.com/gridlab-d/tools/branches/klu-build-update/solver_klu/source/KLU_DLL`

we had to change how to deploy the library,

Download this zip file to a temp directory
[KLU_DLL.zip](https://github.com/pnnl/tesp/files/14676050/KLU_DLL.zip)

In the tesp.sh file you downloaded, comment out or remove this line
`# svn export https://github.com/gridlab-d/tools/branches/klu-build-update/solver_klu/source/KLU_DLL`
add this line in it's place
`unzip -q "[temp directory]/KLU_DLL.zip" -d ./KLU_DLL`
The temp directory and path should be absolute path like "/home/hay/KLU_DLL.zip', no relative path
Be sure to save and exit the file.

Now remove the bad install
`rm -rf $HOME/tesp/`
and then run as before 
`./tesp.sh gitname gitemail`
