### ISSUE TITLE
Add/edit docstrings to gld_feeder_generator.py

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#149]
The existing functions/methods in gld_feeder_generator.py have incomplete or missing docstrings. These need to be updated to conform to the latest format we use in TESP and expanded for clarity.

**Comment by jk1066** [comment]
Update: 
- Added docstrings where missing
- Edited docstrings where incomplete or out of date
- Flagged unused variables with `TODO: remove?`

Status: Incomplete

**Comment by trevorhardy** [comment]
Is this complete?

**Comment by jk1066** [comment]
Yes
