### ISSUE TITLE
SGIP running issue

### ISSUE THREAD

**Issue by gss1721** [pnnl/tesp#15]
When I follow the instruction and installed the software in ubuntu16.04.But I met the issue when I run the sgip examples.
guo@ubuntu:~/tesp/examples/sgip1$ python3 plots.py SGIP1a

File SGIP1a has baseMVA 100.0

Generator Dictionary:
Unit Bus Type Pnom Pmax Costs[Start Stop C2 C1 C0]
1 1 pv 163.0 247.0 [ 500.0 0.0 0.03 1.3 180.0 ]
2 2 swing 0.0 192.0 [ 2000.0 0.0 0.085 3.0 100.0 ]
3 3 pv 85.0 128.0 [ 3000.0 0.0 0.122 5.0 135.0 ]
4 9 pq 0.0 250.0 [ 3000.0 0.0 3.0 50.0 1500.0 ]
5 7 pq 0.0 0.0 [ 0.0 0.0 0.0 0.0 0.0 ]

FNCS Bus Dictionary:
Bus Pnom Qnom ampFactor [GridLAB-D Substations]
7 100.0 35.0 20.0 ['SUBSTATION7']
Traceback (most recent call last):
  File "plots.py", line 6, in <module>
    pp.process_pypower (rootname)
  File "/home/guo/miniconda3/lib/python3.7/site-packages/tesp_support/process_pypower.py", line 61, in process_pypower
    lst_b = json.loads(lp_b)
  File "/home/guo/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/guo/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/guo/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I think it maybe compatible issue.how to fix that?

**Comment by temcdrm** [comment]
How big are your *metrics.json files?

**Comment by gss1721** [comment]
it just showed a title and no contents inside

**Comment by gss1721** [comment]
maybe something wrong, It works when I restart the system

**Comment by temcdrm** [comment]
User resolved it.
