### ISSUE TITLE
Add documentation on running Rates

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#161]
Add a documentation page similar to the "Getting Started" for DSO+T that shows how to run a Rates case and which parameters are generally adjusted. This is to help users actually run the case, not necessarily understand any new code the Rates case has implemented.

**Comment by jk1066** [comment]
Added "Select a Rate Design" section to the Getting Started documentation. Will review internally before marking as complete.

**Comment by trevorhardy** [comment]
Close when  #162 is complete.

**Comment by trevorhardy** [comment]
#162 is complete to closing this as well.
