### ISSUE TITLE
Add documentation on Rates code changes

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#162]
Add a technical overview page for the Rates cases that provides an overview of the Rates analysis and describes the changes made to the DSO+T study to implement Rates. Any publications on Rates should be referenced here (or added once published).

**Comment by trevorhardy** [comment]
Added to the existing DSO+T page (since the functionality and code location are in DSO+T).

**Comment by trevorhardy** [comment]
Need to add documentation on how to run using all of the Rates cases.

**Comment by trevorhardy** [comment]
@jk1066, @d3j331 and @trevorhardy think this is done. Do you know anything we don't or can we consider this complete?

**Comment by jk1066** [comment]
Added some additional guidance on post-processing based on @Hayden-Reeve's _Rates Analysis Post-processing Workflow_ to the Getting Started page. I'd say this can be closed.
