### ISSUE TITLE
helics::RegistrationFailure

### ISSUE THREAD

**Issue by yrgabriel** [pnnl/tesp#163]

**Comment by yrgabriel** [comment]
hello, After I has installed the tesp and test "exec python3 autotest.py &> short.log". Here is a problem about broker_address.

here is part of the short.log:
==  Run:  Weather Agent - HELICS
  latitude 32.9
  longitude -97.017
  altitude 171.0 m
  TZmeridian -90.0
====  Helics Broker Start in
        /home/yingrui/tesp/examples/capabilities/weatherAgent
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yingrui/tesp/venv/lib/python3.8/site-packages/tesp_support/weather/weather_agent.py", line 50, in startWeatherAgent
    broker_address = conf['broker_address']
KeyError: 'broker_address'

I'm really eager that someone could help me. Thank you very much!!!

**Comment by yrgabriel** [comment]
After I add broker_address = conf.get('broker_address', None) into /weather_agent.py, it worked. That's because weather_agent.py could give a address automatically. 
here is a new problem:
==  Run:  TE30 - HELICS Market
====  Helics Broker Start in
        /home/yingrui/tesp/examples/capabilities/te30
terminate called after throwing an instance of 'helics::RegistrationFailure'
  what():  Unable to connect to broker->unable to register federate
Aborted (core dumped)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yingrui/tesp/venv/lib/python3.8/site-packages/tesp_support/api/bench_profile.py", line 53, in no_profiler
    response = func(*args, **kwargs)
  File "/home/yingrui/tesp/venv/lib/python3.8/site-packages/tesp_support/api/tso_PYPOWER.py", line 108, in tso_pypower_loop
    hFed = helics.helicsCreateValueFederateFromConfig(helicsConfig)
  File "/home/yingrui/tesp/venv/lib/python3.8/site-packages/helics/capi.py", line 3635, in helicsCreateValueFederateFromConfig
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-1] Unable to connect to broker->unable to register federate
Program terminated: EnergyPlus Terminated--Error(s) Detected.
terminate called after throwing an instance of 'EnergyPlus::FatalError'
  what():  Error in ExternalInterface: HELICS federate not initialized. Check EnergyPlus *.err file.
Aborted (core dumped)

**Comment by trevorhardy** [comment]
I spoke with @d3j331 and he says the fix will be pretty easy. I'm hoping we can get that to you soon.

**Comment by yrgabriel** [comment]
Sorry, could you tell me why this error happen? Maybe I can  fix it by myself. @d3j331

**Comment by trevorhardy** [comment]
We've been tied up with competing projects; sorry this has taken us so long to address. @d3j331, do you have an ETA on this fix?
