### ISSUE TITLE
library libstdc++-6.dll.

### ISSUE THREAD

**Issue by GONGHJ** [pnnl/tesp#17]
![image](https://user-images.githubusercontent.com/6056795/58130454-08b2a580-7bea-11e9-8683-43e8a5ef82c2.png)

Hello Tom,
When executing python prepare_case.py, I encountered the problem "The procedure entry point .... dynamic link library libstdc++-6.dll." Any suggestions on tackling it.

Thanks,

Huangjie

**Comment by temcdrm** [comment]
All dependencies are now included with the Linux installer and/or Docker container. Suggest running in a VM or Docker.
