### ISSUE TITLE
Running examples Problem

### ISSUE THREAD

**Issue by SamyFaddel** [pnnl/tesp#18]
Hello,

I am new to tesp. I followed the instructions for installing the software. I checked the paths in the shell and everything is ok.
C:\Users\Samy>set tesp
TESPDIR=C:\Users\Samy\tesp

C:\Users\Samy>set glpath
GLPATH=C:\tesp_exec\bin;C:\tesp_exec\lib\gridlabd;C:\tesp_exec\share\gridlabd

However, for some reason I can not run the given examples and generate the results.
For example, when I tried to run the loadshed example, I noticed that I have lower number of communication connection as follows and I do not get the results:
  TCP    0.0.0.0:5570           0.0.0.0:0              LISTENING       3856
  TCP    127.0.0.1:5570         127.0.0.1:52217        ESTABLISHED     3856
  TCP    127.0.0.1:52217        127.0.0.1:5570         ESTABLISHED     22040

In the generated gridlab-d text, I have error as follow:
ERROR    [INIT] : gldcore/module.c(422): module 'connection' load failed - "C:\tesp_exec\lib\gridlabd\connection.dll": The specified module could not be found.
loadshed.glm(17): module 'connection' load failed, No such file or directory
loadshed.glm(17): load failed at or near 'module conne...'
ERROR    [INIT] : unable to load 'loadshed.glm': No such file or directory
FATAL    [INIT] : shutdown after command line rejected

I double checked the existence of this module and it is there?

Any idea regarding this issue?

**Comment by temcdrm** [comment]
All dependencies are now included with the Linux installer and/or Docker container. Suggest running in a VM or Docker if using Windows.  Please note that the retail version of GridLAB-D may not include the connection module for co-simulation, so you want to make sure that TESP finds a cosimulation-enabled version of GridLAD-D first.
