### ISSUE TITLE
JSON files

### ISSUE THREAD

**Issue by jrupamathi** [pnnl/tesp#2]
Hi,

I seem to be having some issue with accessing the JSON files. When I run any of the examples suggested, I end up with the same error. Please see the screenshot below:
![image](https://user-images.githubusercontent.com/6997177/26887966-a775b914-4b77-11e7-9057-8229e35fdbbd.png)

I looked at the script and it seems like for some reason, it is unable to create and/or open JSON files
Please let me know if I missed something and how can this be resolved.

Thanks,
Rupa

**Comment by temcdrm** [comment]
Rupa - the "Miniconda2" implies that Python 2 has been invoked.  TESP requires Python 3.

**Comment by jrupamathi** [comment]
Thank you very much. That worked.
