### ISSUE TITLE
Running example "SGIP1" bumps into ERROR

### ISSUE THREAD

**Issue by eigenpi** [pnnl/tesp#20]
Installed TESP ok. When testing example "sgip1" I run into an issue related to, I think, gridlab.
The content of gridlabd1a.log is this:

"ERROR    [INIT] : connection: local variable '"RegionalWeather".wind_speed' cannot be resolved"

triggered by the gridlab launching command from runSGIP1a.sh script:
"(export FNCS_FATAL=YES && exec gridlabd -D USE_FNCS -D METRICS_FILE=SGIP1a_metrics.json SGIP1b.glm &> gridlabd1a.log &)"

Any ideas where to start to troubleshoot? Thanks!

**Comment by temcdrm** [comment]
We probably got ahead of ourselves in updating the Python support package on pypi.  From a terminal, please issue "pip install tesp_support==0.3.1" and try again.  If that doesn't work, please let us know the operating system, and whether or not you installed the Docker version.

**Comment by eigenpi** [comment]
Dear Tom, Yes, that seems to have fixed my issue. Thanks a lot for the very prompt response! Best, Cris.
