### ISSUE TITLE
Example problems

### ISSUE THREAD

**Issue by czekster** [pnnl/tesp#22]
1. When running **comm**: does not generate files and yields "KeyError: 'TimeStep'
2. When running **loadshed** (with ns-3): the Makefile is not in the folder, so make does not work.
Version is the latest: tesp-0.6.0-linux-x64
Downloaded on 04/28/2020

**Comment by temcdrm** [comment]
Thanks for looking at this. We fixed the missing Makefile but the first item should have worked.  Can you please check what "`pip3 show tesp_support`" returns and then try "`pip3 install tesp_support --upgrade --no-cache-dir`"?

**Comment by czekster** [comment]
> 
> 
> Thanks for looking at this. We fixed the missing Makefile but the first item should have worked. Can you please check what "`pip3 show tesp_support`" returns and then try "`pip3 install tesp_support --upgrade --no-cache-dir`"?

Yes - my fault, now it's working. Thank you.
