### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by temcdrm** [pnnl/tesp#29]
Drawings:

- _overview block diagram with updated federates in HELICS_
- message flows for the MATPOWER/MOST example
- message flows for the three-building example with consensus mechanism
- diagram of the relationship between meters, nodes and loads in GridLAB-D, including three-phase commercial transformers
- update the existing UML
- Docker image contents

New text:

- sample results and description for each example in readme; link to RTD
- jsonschema for the ercot_8.json, case_config.json, eplus_config.json, eplus_msg.json and eplus_agent_msg.json files
- updated inline comments for Python files that compile into RTD
- incorporate the table of E+ reference building characteristics and thumbnails
- link to the summary of PNNL taxonomy feeder characteristics and footprints
- incorporate table of FNCS vs. HELICS solution times
- describe how to run the University of Pittsburgh machine learning examples

New introductory video on https://www.youtube.com/channel/UCMKOTNGldZ3OdDzHRJ_myeg 

- install on a VM or Docker
- configure a case and run it
- read the metrics and make a custom plot
- make a new OpenDSS agent

**Comment by trevorhardy** [comment]
Have these been implemented? If so, I'm not seeing them. For example, I would have expected the [Design Reference page](https://tesp.readthedocs.io/en/latest/Design_Reference.html) to refer to MOST instead of AMES.

**Comment by temcdrm** [comment]
This is a to-do list for the documentation.  The code and examples have been implemented.

**Comment by trevorhardy** [comment]
Documentation is an on-going struggle in TESP and I'm going to close this for now and add individual issues as needed.
