### ISSUE TITLE
Installer permissions for pip3

### ISSUE THREAD

**Issue by temcdrm** [pnnl/tesp#31]
The installer script must run with _sudo_ to install binaries to _/opt/tesp_. As a result, Python packages have to be installed or removed later with _sudo_, e.g., _sudo pip3 uninstall packagename_

Also see this error message from InstallBuilder's debug mode, when trying **--no-cache-dir**

Script stderr:
 The directory '/home/tom/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/tom/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Without  **--no-cache-dir**, those errors don't appear, but PSST isn't upgraded from 0.1.6 to 0.1.9.

The installer can be run in debug mode: **sudo installer_name.run --enable-debugger**

**Comment by trevorhardy** [comment]
No longer an issue under new installer.
