### ISSUE TITLE
ns-3 example not working in optimized mode on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by temcdrm** [pnnl/tesp#32]
The **loadshed/runhpy.sh** example works on Ubuntu 18.04 LTS, with ns-3 in either debug or optimized mode

On Ubuntu 20.04 LTS, a coredump occurs in optimized mode, but it runs in debug mode. 

This example involves building **loadshedCommNetwork** with gcc9 on Ubuntu 20.04 LTS, against ns-3 built with gcc7 on Ubuntu 18.04 LTS.  On Ubuntu 18.04 LTS, everything was built with the same gcc version and options.

For now, TESP ships with both debug and optimized builds of ns-3, and runhpy.sh configured to run in debug mode.  The debug mode enables ns-3 to produce logging output, but the executables are larger and slower than in optimized mode.

**Comment by trevorhardy** [comment]
@laurmarinovici, have you tried this with your updated loadshed example?

**Comment by trevorhardy** [comment]
@d3j331; can you confirm if this is still an issue?

**Comment by d3j331** [comment]
It works in 22.04 as optimized build using gcc11

**Comment by trevorhardy** [comment]
Good enough for me; case closed.
