### ISSUE TITLE
v1.0.0 incorrect install on Ubuntu LTS 20.04

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#36]
Using a clean VirtualBox VM install of Ubuntu LTS 20.04.1 the tesp installer runs to completion but the installation doesn't run properly.

- $PATH was not appended to include `/opt/tesp/bin`
- `make_tesp_run_dir.sh` errors out and does not create the tesp directory correctly:
```
cp: cannot state '/share/examples': No such file or directory 
cp: cannot state '/share/ercot': No such file or directory 
cp: cannot state '/share/autotest.py': No such file or directory 
cp: cannot state '/share/autotest_long.py': No such file or directory 
```
There is no `/share` in file system; I don't know if there should be one.

**Comment by trevorhardy** [comment]
It looks like `$TESP_INSTALL` also hadn't been set in the installation process. Setting that environment variable and re-running the command cleared it up.

After reviewing the ["Installing on Linux"](https://tesp.readthedocs.io/en/stable/Installing_Ubuntu_Link.html) section on RTD I see that there is a sentence in there that `$TESP_INSTALL`  needs to be set. Can setting these environmental variables be part of the installation process, adding them to the appropriate login script?

**Comment by temcdrm** [comment]
The environment variables should have been set during the installation; this was tested in Ubuntu 20.04 LTS inside VirtualBox. It should have put [this file](https://github.com/pnnl/tesp/blob/develop/install/Linux/helpers/tesp_envar.sh) into /etc/profile.d

Is that file present?  Did you change the default location during installation? Had you logged out and logged back in after the first installation?

**Comment by trevorhardy** [comment]
tesp_envar.sh was in /etc/profile.d.

I can't recall if I logged out or not so let's assume I didn't.

I logged out and logged back in again and $PATH is now correct.
