### ISSUE TITLE
v1.0.0 loadshed/runhjava.sh does not run

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#38]
Running the examples/loadshed.runhjava.sh fails:

```
helicshed.java:1: error: package com.java.helics does not exist
import com.java.helics.helics;
                      ^
helicshed.java:2: error: package com.java.helics does not exist
import com.java.helics.*;
^
helicshed.java:7: error: cannot find symbol
	System.out.println ("HELICS Version: " + helics.helicsGetVersion());
	                                         ^
  symbol:   variable helics
  location: class helicshed
helicshed.java:8: error: cannot find symbol
	SWIGTYPE_p_void fi = helics.helicsCreateFederateInfo();
	^
  symbol:   class SWIGTYPE_p_void
  location: class helicshed
helicshed.java:8: error: cannot find symbol
	SWIGTYPE_p_void fi = helics.helicsCreateFederateInfo();
	                     ^
  symbol:   variable helics
  location: class helicshed
```

among many others; I assume they are all related

**Comment by temcdrm** [comment]
what OS and what version of HELICS?

**Comment by trevorhardy** [comment]
I ran the TESP installer on a VirtualBox VM with a clean installation of Ubuntu LTS 20.04.1

**Comment by trevorhardy** [comment]
Still failing for me with same error after logout and login back in.

**Comment by temcdrm** [comment]
Can you see if this version of runhjava.sh works?

javac -classpath ".:$TESP_INSTALL/java/helics.jar" helicshed.java
(exec helics_broker -f 2 --loglevel=3 --name=mainbroker &> broker.log &)
(exec gridlabd -D WANT_HELICS_NO_NS3 loadshed.glm &> gridlabd.log &)
(exec java -classpath ".:$TESP_INSTALL/java/helics.jar" -Djava.library.path="$TESP_INSTALL/java" helicshed &> java.log &)

**Comment by trevorhardy** [comment]
Looks like it works for me; I can plot graphs.

**Comment by temcdrm** [comment]
It may have been a side effect of using /etc/profile.d to set the environment.  This version of runhjava.sh is probably better anyway so I will check it in.

**Comment by trevorhardy** [comment]
Sounds good; thanks!
