### ISSUE TITLE
fncs library not found

### ISSUE THREAD

**Issue by chicodelarosa** [pnnl/tesp#4]
Under the **FNCS with Prerequisites** section of the documentation I get the "_fncs library not found_" error when executing "cmake ..":
```
-- Could NOT find FNCS (missing:  FNCS_INCLUDE_DIR FNCS_LIBRARY)
CMake Error at CMakeLists.txt:23 (MESSAGE):
  fncs library not found

-- Configuring incomplete, errors occurred!
See also "/root/src/fncs/java/build/CMakeFiles/CMakeOutput.log".
```
I am working on an Ubuntu 16.04.3 LTS virtual machine with GCC/G++ 5.4.0 20160609.

**Comment by ikdmob** [comment]
I have the same problem, did you figure out a solution?

**Comment by temcdrm** [comment]
All dependencies are now included with the Linux installer and/or Docker container.
