### ISSUE TITLE
Migrate Energy+ integration to TESP repo

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#42]
Move Energy+ integration for TESP from FNCS repo to TESP repo

**Comment by temcdrm** [comment]
I think we (Heng) should consider a pull request into the main EnergyPlus branch instead.

**Comment by trevorhardy** [comment]
Main EnergyPlus branch of which repository?

**Comment by trevorhardy** [comment]
@temcdrm, which repository do you think our EnergyPlus changes should be submitted to?

**Comment by temcdrm** [comment]
Our FNCS and HELICS native integration is here: https://github.com/FNCS/EnergyPlus/tree/fncs_9.3.0

We, i.e., Heng, should make a branch and then pull request here: https://github.com/NREL/EnergyPlus.  This way, our native HELICS integration could stay in synch with future versions of EnergyPlus.  Right now, it's a manual process.

**Comment by trevorhardy** [comment]
Agreed. @xcosmos6, is the HELICS Energy+ integration at a point where you can make a PR into the main E+ repo?

**Comment by trevorhardy** [comment]
With the new version of E+ that provides a Python interface, our next upgrade of E+ will use this interface instead of the custom energy management system that is enabling co-simulation.
