### ISSUE TITLE
-ljsoncpp not found

### ISSUE THREAD

**Issue by chicodelarosa** [pnnl/tesp#5]
I get _-ljsoncpp not found_ when executing the "gridlabd --validate" command under the **GridLAB-D with Prerequisites** section of the instructions for **Building on Ubuntu**.

I am working on an Ubuntu 16.04.3 LTS virtual machine with GCC/G++ 5.4.0 20160609.

**Comment by temcdrm** [comment]
All dependencies are now included with the Linux installer and/or Docker container.
