### ISSUE TITLE
Inconsistent shape of metrics files

### ISSUE THREAD

**Issue by allisonmcampbell** [pnnl/tesp#52]
(At least) two metrics files have different shapes accounting for the time stamps / hours

The pypower metrics files -- {case}_m_dict.json, bus_{case}_metrics.json, gen_{case}_metrics.json -- all have 577 time stamps.
The GLD metrics files -- {case}_glm_dict.json, substation_{case}_metrics.json, house_{case}_metrics.json, billing_meter_{case}_metrics.json, inverter_{case}_metrics.json, capacitor_{case}_metrics.json, regulator_{case}_metrics.json -- all have 576 time stamps.

The inconsistency comes from the GLD metrics files not having an entry for time = '0' (zero), whereas this exists (with content) for the pypower metrics files.

**Comment by trevorhardy** [comment]
We're going to address this in our API re-work where we hope to have a more consistent data management strategy.
