### ISSUE TITLE
Te30 example of TESP

### ISSUE THREAD

**Issue by AliArdeshirilajimi** [pnnl/tesp#55]
I am using aTESP toolbox and I want to implement TESP according to your website guide and documentation through Using Docker and the autotest.py script option. after following the documentation, I received the error about line four of the prepare_case.py file, the error is:

Traceback (most recent call last) :
     File "prepare_case.py", line 4, in <module>
            tmy_file = os.getenv('TESP_INSTALL') + '/share/support/weather/AZ-Tucson_International_Ap.tmy3'
 TypeError: Unsupported operand type(s) for +: 'NoneType' and 'str' .

according to the documentation I install all required support files, However, I deal with this problem, please let me know what is the solution! In addition, there is a YouTube tutorial on the TESP website to install TESP on windows, however, the tesp-0.1.0-windows-installer.exe file does not exist on the GitHub website, is there any other option to install TESP on windows?

**Comment by trevorhardy** [comment]
Did you set the `TESP_INSTALL` environment variable? The error message makes me think that it is not. On Linux you can type `echo $TESP_INSTALL` to see if it has been set. If it has been set it will return a path and if it has not, it will return nothing.

We've dropped support for Windows and Mac and only support Linux at present. I use a Mac myself and have TESP installed in a VirtualBox VM. It's been working well for me.
