### ISSUE TITLE
Error when running examples with pypower co-simulated over FNCS

### ISSUE THREAD

**Issue by Yuanliang-Li** [pnnl/tesp#57]
Hi,

This is a strange problem when I trid to use TESP and ran some examples from [Running Examples](https://tesp.readthedocs.io/en/latest/Running_Examples_Link.html#running-examples). I mainly focused on loadshed and te30 examples.

This problem is that I was able to run examples with pypower co-simulated over HECLIS successfully, but fail in running examples with pypower co-simulated over FNCS. If the examples do not include pypower federate, I can successfully run them over both HELICS and FNCS. This conclusion comes from many of my experiments following right steps.

First, I want to show my basic settings,
OS: Linux Mint 20.2
User: root
TESP version: 1.0.0
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/tesp:/opt/tesp/bin:/opt/tesp/PreProcess:/opt/tesp/PostProcess
TESP_INSTALL: /opt/tesp

Before executing the run.sh (or other version, e.g., runh.sh, runpp.sh) of each example, I always execute ./clean.sh, ./kill5570.sh, ./kill23404.sh for many times. For te30 example, python3 prepare_case.py is also executed in advance to prepare the case.

Then, I can run successfully the following examples:
1. loadshed - GridLAB-D and Python over HELICS   (without Pypower)
2. loadshed - GridLAB-D and Python over FNCS   (without Pypower)
3. energyplus - EnergyPlus over HELICS   (without Pypower)
4. energyplus - EnergyPlus over FNCS   (without Pypower)
5. pypower - PYPOWER over HECLIS   (include Pypower)
6. TE30 - case with market over HELICS   (include Pypower)

I fail in running the following examples:
7. pypower - PYPOWER over FNCS (include Pypower)
8. TE30 - case with market over FNCS (include Pypower)

For case 7 (pypower - PYPOWER over FNCS), the content in pypower.log is:
```
cat pypower.log 
unit   2 off from 108000 to 154800
ERROR: could not parse time value
WARNING: fncs is not initialized
```

For case 8 (TE30 - case with market over FNCS), the content in pypower.log is:
```
cat pypower.log
unit   2 off from 108000 to 154800
ERROR: could not parse time value
WARNING: fncs is not initialized
```
There is no content is broker.log and gridlabd.log. 

So, I guess it could be some problems in the integration of the pypower federate over FNCS. 

I wish I can get reply for this issue. 

Many thanks!

**Comment by trevorhardy** [comment]
We are on the verge of releasing an updated version of TESP that will begin the process of dropping FNCS support. It is unlikely we will be able to prioritize debugging this particular issue. Is there a reason that you need to use FNCS to run these examples over HELICS?

**Comment by Yuanliang-Li** [comment]
> We are on the verge of releasing an updated version of TESP that will begin the process of dropping FNCS support. It is unlikely we will be able to prioritize debugging this particular issue. Is there a reason that you need to use FNCS to run these examples over HELICS?

**Comment by Yuanliang-Li** [comment]
> We are on the verge of releasing an updated version of TESP that will begin the process of dropping FNCS support. It is unlikely we will be able to prioritize debugging this particular issue. Is there a reason that you need to use FNCS to run these examples over HELICS?

Thanks. Actually, My team is working on a project based on TE30 from TESP. In the README.md of TE30, we can see instructions on running te30 by using run.sh and run0.sh. But no instructions about runh.sh and runh0.sh. So, we just worried about if there will be some issues and just ran examples over FNCS. 

But we are clear now. Thanks
