### ISSUE TITLE
error in code in energplus in pnnl/tesb

### ISSUE THREAD

**Issue by karuneshm95** [pnnl/tesp#62]
object src/EnergyPlus/CMakeFiles/energypluslib.dir/DXCoils.cc.o
{standard input}: Assembler messages:
{standard input}:118818: Warning: end of file in string; '"' inserted
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/EnergyPlus/CMakeFiles/energypluslib.dir/build.make:440: src/EnergyPlus/CMakeFiles/energypluslib.dir/DXCoils.cc.o] Error 1
make[2]: *** Deleting file 'src/EnergyPlus/CMakeFiles/energypluslib.dir/DXCoils.cc.o'
make[1]: *** [CMakeFiles/Makefile2:1477: src/EnergyPlus/CMakeFiles/energypluslib.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
karunesh@RADHEYKRISHNA:~/usrc/EnergyPlus/build$

**Comment by trevorhardy** [comment]
We are in process of updating TESP; can you try installing from the "evolve" branch to see if this solves hour problems?  [Instruction are here](https://tesp.readthedocs.io/en/evolve/Installing_Building_TESP.html) though the wget command is slightly different since we haven't pushed the changes to the main branch yet.

```
wget https://raw.githubusercontent.com/pnnl/tesp/evolve/scripts/tesp.sh
```

**Comment by karuneshm95** [comment]
i tried to install using evolve repository and installing by command ./tesp.sh but instead ns-3 is not installing and ./versions.sh is not working

**Comment by trevorhardy** [comment]
What OS are you using? We've only been testing this on Ubuntu 20.04.

**Comment by trevorhardy** [comment]
I just re-ran the installation process on a fresh Ubuntu 20.04 VM and it worked fine:

```
wget https://raw.githubusercontent.com/pnnl/tesp/evolve/scripts/tesp.sh
chmod 755 ./tesp.sh
./tesp.sh trevorhardy trevor.hardy@pnnl.gov
```

I chose to not to build the binaries.

The versions check passed fine as well:
```
FNCS installed

Helics, 2.8.0 (2021-09-17)

GridLAB-D 4.3.0-18923 (Navajo [107009aa:develop]) 64-bit LINUX RELEASE

EnergyPlus, Version 9.3.0-fd4546e21b (No OpenGL)

NS-3 installed

Ipopt 3.13.2 (x86_64-pc-linux-gnu), ASL(20190605)
```

So this process isn't working for you?

**Comment by trevorhardy** [comment]
Is this still an issue?

**Comment by d3j331** [comment]
No reply, closing the issue
