### ISSUE TITLE
not able to build ns-3 using evolve by direct 

### ISSUE THREAD

**Issue by karuneshm95** [pnnl/tesp#63]
git clone -b evolve http: 
./tesp.sh
but failed to build & install  ns-3 by direct using command
karunesh@RADHEYKRISHNA:~/Desktop/tesp$ cd scripts
karunesh@RADHEYKRISHNA:~/Desktop/tesp/scripts$ ./tesp.sh Karuneshm9 karuneshm95@gmail.com
Helics, 3.1.0 (2021-11-24)

GridLAB-D 4.1.0-17900 (Lugo [e8ec2c43:HEAD:Mod]) 64-bit LINUX RELEASE

./versions.sh: line 25: energyplus: command not found

NS-3 not installed

Ipopt 3.13.2 (x86_64-pc-linux-gnu), ASL(20190605)

**Comment by trevorhardy** [comment]
I tried replicating this with a fresh Ubuntu 20.04 VM and was able to get a successful install.

```
sudo apt install git
git clone -b evolve https://github.com/pnnl/tesp.git
cd ./tesp/scripts
./tesp.sh trevorhardy trevor.hardy@pnnl.gov
```

Output:
```
++++++++++++++  Compiling and Installing TESP software is complete!  ++++++++++++++

FNCS installed

Helics, 2.8.0 (2021-09-17)

GridLAB-D 4.3.0-18923 (Navajo [107009aa:develop]) 64-bit LINUX RELEASE

EnergyPlus, Version 9.3.0-fd4546e21b (No OpenGL)

NS-3 installed

Ipopt 3.13.2 (x86_64-pc-linux-gnu), ASL(20190605)


++++++++++++++  TESP versions has been installed! That's all folks!  ++++++++++++++
```

Anything you're doing differently?

**Comment by Karuneshm9** [comment]
I have done the reinstall process again but showing error in installing energy plus.
![16392191079023688951056905838144](https://user-images.githubusercontent.com/95308543/145673585-07201f88-db3c-4852-8186-7f37be91fb84.jpg)
![16392193570743832119855134746155](https://user-images.githubusercontent.com/95308543/145673664-291104c0-f71c-45a5-bd68-2e60b53b65a9.jpg)
Always stop at here

**Comment by Karuneshm9** [comment]
![16392213699874011054208909364524](https://user-images.githubusercontent.com/95308543/145674506-5dadeff1-78a2-485d-ad7d-6bb0209db8a2.jpg)
Finally this error

**Comment by trevorhardy** [comment]
Can you try installing the binaries directly rather than building from source? (You may need to re-download "tesp.sh" as this is a new install feature we recently added.)

We don't manage the energyPlus code-base so if it is failing to build [you'll likely have to go to them to get support](https://github.com/NREL/EnergyPlus). I'm hoping we can avoid that by just installing the binaries directly.

**Comment by trevorhardy** [comment]
Is this still an issue or should we close it out?

**Comment by d3j331** [comment]
No reply, closing issue
