### ISSUE TITLE
Not building tesp ns-3 ,energy plus ,directly from command ./trap.sh

### ISSUE THREAD

**Issue by Karuneshm9** [pnnl/tesp#64]
My system is window .I am using Ubuntu 20 version  through window subsystem for linux. I have separately installed gridlabd but in tesp repository ,ns-3 is not building. Please suggest how I able to use your gridlabd when working with tesp . Installing of docker is needed to work . I have tried many times bit same problem

**Comment by trevorhardy** [comment]
Are you able to build ns-3 on its own, outside of TESP? Try getting the [latest source from ns-3](https://www.nsnam.org/releases/) and following their build process to see if it works. If it does then we can figure out what's different between the two version or build processes.

**Comment by d3j331** [comment]
Not using Windows at this point
