### ISSUE TITLE
Helics is not building through code &not interfacing with ns-3 & grudlabd

### ISSUE THREAD

**Issue by Karuneshm9** [pnnl/tesp#66]
Please check with each installation ,helics is not building from helics code &also not integrating with ns-3 & gridlabd . I have used your response 0.8 version &try to install but there is error in belive building from GMLC/TDC/HELICS  in github. Also not integrating with ns-3 with belive using helics-src &ns-3 develop.
Please help
Please run individually with your code &also check your interfacing two at a time

**Comment by trevorhardy** [comment]
I'll double-check that HELICS was building properly but I'm 99% sure when I last tested the installation process a week or two ago that the HELICS-based load-shed examples were working.

I would believe that the ns-3 integration with HELICS is not working fully; we'e been working on it for a number of weeks in coordination with the HELICS project. @laurmarinovici, do you know what the state of ns-3 in TESP is?

**Comment by d3j331** [comment]
This has been built and examples auto tests have been run in v1.2.2 with success.
