### ISSUE TITLE
PyPOWER, Numpy and Python v3.10

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#85]
It looks like PyPOWER, which is no longer maintained, requires an older version of numpy (v1.21.5)  that is not the default version in Python v3.10 and later (installs numpy v1.23). The newer version has deprecated the `asscalar()` method which is used by PyPOWER.

It seems like if we want to continue using PyPOWER we'll need to do some patching on our end (assuming there is a simple-enough) work-around. PyPOWER is no longer being actively maintained.

**Comment by d3j331** [comment]
The requirement.txt has been updated to locked in a version for pypower, pyutillib, pyomo, docutils, numpy  > Tesp 1.1.5

**Comment by trevorhardy** [comment]
@d3j331, is this issue resolved?
