### ISSUE TITLE
Redundancy when using `add_obj()` API in new feeder_generator code

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#95]
I think we should force "obj_id" in the feeder_generator namespace to always be equal to "name" in the GridLAB-D model namespace. Doing so can simplify the user-facing aspects of the API as well as prevent mistakes or accidental inconsistency from making the functionality we're providing harder to use.

I would be in favor of requiring all GridLAB-D object instances that are added to a GridLAB-D model via this API to have the "name" parameter defined. This would allow us to equivocate the GridLAB-D object instance's name and the name by which we refer to it when using this API.  Doing so would also allow us to simplify the `add_obj()` API call. Getting a little bit polymorphic we could have two versions:

1. Don't specify the "obj_id" in the API call  but require it to exist in the parameter list/dictionary for the object instance being added. Use the defined "name" in that parameter list/dictionary to define the feeder_generator's "obj_id".
2. Don't specify the parameter list/dictionary in the API call but require the "obj_id" instead. We use "obj_id" to add the "name" parameter to the GridLAB-D object instance's parameter with the value for that parameter being the provided "obj_id".

There might be a better way of doing this but the goal is to require users to only specify this unique ID in one place and then use it to define the value in the other place.

**Comment by trevorhardy** [comment]
We might need more discussion on this; let's see if we can figure out the best way to do this and get it implemented.

**Comment by trevorhardy** [comment]
Completed buy not merged into `develop` branch yet.

**Comment by d3j331** [comment]
in tesp_support 1.3.1  

    glmMod = GLMModifier()
    feeder_path = os.path.join(feeders_path, feeder_file)
    glmMod.read_model(feeder_path)

    for name, transfomer_item in glmMod.model.transformer.items():
        phase = transfomer_item['phase']
