### ISSUE TITLE
"name" and "obj_id" confusing in new feeder_generator API calls

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#98]
From the user perspective, the "name" and "obj_id" fields are not intuitive names since a user is thinking in terms of the GridLAB-D objects being added, removed, and edited and not data structure they are actually manipulating to achieve these ends. 

As a GridLAB-D user, I would think "name" would refer to the GridLAB-D object instance name and not the type of GridLAB-D object. Similarly, I didn't understand what the "obj_id" referred to.

I don't know the best way to resolve this. A refactor addressing those parameter names, if it can be done quickly, might be good enough. Maybe we add another syntax sugar layer on top of the existing API to hide those parameter names?

**Comment by trevorhardy** [comment]
Where are we at with this?

**Comment by trevorhardy** [comment]
We learned the .glm "object" defines the namespace meaning that you can't have a house named "Bob" and a transformer named "Bob". This will allows us to tweak or add an API to look for an object with a specific name regardless of the class.

**Comment by d3j331** [comment]
This has been close:
gld_type (formerly name) and name (formerly obj_Id) have been rename.
'gld_type' gives the name of the module or object class (i.e. house, transformer ).
'name' gives the name of the instance of module or class.
All instances have to be unique for all classes.
