### ISSUE TITLE
Entity object should be iterable

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#99]
In trying out the new feeder_generator API I've found that I need to pull in both the GLD object instances through `GLMModifier.get_objects()` to get the objects themselves and then I need to make a list of the object instance names (the keys of the `.instance()` dictionary) so that I can iterate through them.

It would be convenient for users if it was possible to directly iterate over `GLMModifier.get_objects()`; something like this:

```
for obj_name_str, obj_params_dict in GLMModifier.get_objects('node'):
    if 'CS' in obj_params_dict['phases']:
        # Do something amazing
```

**Comment by trevorhardy** [comment]
I know we've been messing around with this and we might be done. If we've got this working, add a comment showing how do it.

**Comment by trevorhardy** [comment]
Mitch is going to look into it.

**Comment by d3j331** [comment]
this is how its going to be used in tesp_support 1.3.1

transformer_vals = glmMod.get_object_vals('transformer')
for name, transformer in transformer_vals.items():
        phase = transformer['phases']

'name' is the name for the instance of the object.
'transformer' is the dictionary of the instance.
